export default [
  {
    name: "University de Yaounde I",
    acronym: "UYI",
    location: "Yaounde",
    country_ranking: 1,
    world_ranking: 7269,
    majors: ["Arts and Humanaties", "Business and Social Sciences",
              "Medicine and Health", "Engineering", "Science and Technology"],
    is_public: true,
    is_non_profit: true,
    date_founded: "1962",
    enrollment: "10,000 - 15,000",
    num_faculty: "700 - 800",
    calendar_type: "Semester",
    religious_affiliation: "None",
    has_library: true,
    housing: "Not Reported",
    has_sports_facility: true,
    admission_selection: "Entrance Exams",
    accepts_internationals: true
  },
  {
    name: "University de Dschang",
    acronym: "UDS",
    location: "Dschang",
    country_ranking: 2,
    world_ranking: 8229,
    majors: ["Arts and Humanaties", "Business and Social Sciences",
              "Medicine and Health", "Engineering", "Science and Technology",
              "Language and Cultural"],
    is_public: true,
    is_non_profit: true,
    date_founded: "1993",
    enrollment: "10,000 - 15,000",
    num_faculty: "500 - 600",
    calendar_type: "Semester",
    religious_affiliation: "None",
    has_library: true,
    housing: "Yes",
    has_sports_facility: true,
    admission_selection: "Not Reported",
    accepts_internationals: true
  },
  {
    name: "University de Douala",
    acronym: "UDLA",
    location: "Doala",
    country_ranking: 3,
    world_ranking: 8775,
    majors: ["Arts and Humanaties", "Business and Social Sciences",
              "Engineering", "Science and Technology"],
    is_public: true,
    is_non_profit: true,
    date_founded: "1977",
    enrollment: "8,000 - 9,000",
    num_faculty: "200 - 300",
    calendar_type: "Not Reported",
    religious_affiliation: "None",
    has_library: true,
    housing: "Not Reported",
    has_sports_facility: true,
    admission_selection: "Entrance Exams",
    accepts_internationals: true
  },
  {
    name: "University de Buea",
    acronym: "UB",
    location: "Buea",
    country_ranking: 4,
    world_ranking: 8797,
    majors: ["Business and Social Sciences", "Language and Cultural",
             "Medicine and Health", "Engineering", "Science and Technology"],
    is_public: true,
    is_non_profit: true,
    date_founded: "1992",
    enrollment: "Not Reported",
    num_faculty: "Not Reported",
    calendar_type: "Semester",
    religious_affiliation: "None",
    has_library: true,
    housing: "Not Reported",
    has_sports_facility: true,
    admission_selection: "Entrance Exams / Transcripts",
    accepts_internationals: true
  },
  {
    name: "University de Maroua",
    acronym: "UM",
    location: "Maroua",
    country_ranking: 5,
    world_ranking: 9274,
    majors: [],
    is_public: true,
    is_non_profit: true,
    date_founded: "2008",
    enrollment: "Not Reported",
    num_faculty: "Not Reported",
    calendar_type: "Not Reported",
    religious_affiliation: "None",
    has_library: true,
    housing: "Not Reported",
    has_sports_facility: false,
    admission_selection: "Not Reported",
    accepts_internationals: true
  },
  {
    name: "University de Ngaoundere",
    acronym: "UN",
    location: "Ngaoundere",
    country_ranking: 6,
    world_ranking: 9510,
    majors: ["Business and Social Science", "Language and Cultural",
             "Medicine and Health", "Science and Technology"],
    is_public: true,
    is_non_profit: true,
    date_founded: "1982",
    enrollment: "25,000 - 30,000",
    num_faculty: "300 - 400",
    calendar_type: "Not Reported",
    religious_affiliation: "None",
    has_library: true,
    housing: "Yes",
    has_sports_facility: false,
    admission_selection: "Not Reported",
    accepts_internationals: true
  },
  {
    name: "University Catholique d'Afrique Centrale",
    acronym: "UCAC",
    location: "Yaounde",
    country_ranking: 7,
    world_ranking: 9599,
    majors: ["Arts and Humanaties"],
    is_public: false,
    is_non_profit: true,
    date_founded: "1989",
    enrollment: "1,000 - 2,000",
    num_faculty: "Not Reported",
    calendar_type: "Not Reported",
    religious_affiliation: "Christian-Catholic",
    has_library: true,
    housing: "Not Reported",
    has_sports_facility: false,
    admission_selection: "Not Reported",
    accepts_internationals: true
  },
  {
    name: "University des Montagnes",
    acronym: "UdM",
    location: "Bangangte",
    country_ranking: 8,
    world_ranking: 10719,
    majors: [],
    is_public: false,
    is_non_profit: true,
    date_founded: "2000",
    enrollment: "500 - 1,000",
    num_faculty: "0 - 50",
    calendar_type: "Not Reported",
    religious_affiliation: "None",
    has_library: true,
    housing: "Not Reported",
    has_sports_facility: false,
    admission_selection: "Not Reported",
    accepts_internationals: true
  },
  {
    name: "University de Bamenda",
    acronym: "UDB",
    location: "Bamenda",
    country_ranking: 9,
    world_ranking: 11479,
    majors: [],
    is_public: true,
    is_non_profit: true,
    date_founded: "2011",
    enrollment: "Not Reported",
    num_faculty: "Not Reported",
    calendar_type: "Not Reported",
    religious_affiliation: "None",
    has_library: true,
    housing: "Not Reported",
    has_sports_facility: false,
    admission_selection: "Not Reported",
    accepts_internationals: true
  },
  {
    name: "Catholic University OF Cameroon",
    acronym: "CATUC",
    location: "Bamenda",
    country_ranking: 10,
    world_ranking: 11728,
    majors: [],
    is_public: false,
    is_non_profit: true,
    date_founded: "2010",
    enrollment: "Not Reported",
    num_faculty: "Not Reported",
    calendar_type: "Not Reported",
    religious_affiliation: "Christian-Catholic",
    has_library: true,
    housing: "Not Reported",
    has_sports_facility: false,
    admission_selection: "Not Reported",
    accepts_internationals: true
  },
  {
    name: "Bamenda University of Science and Technology",
    acronym: "BUST",
    location: "Bamenda",
    country_ranking: 11,
    world_ranking: 11771,
    majors: ["Arts and Humanaties", "Science and Technology"],
    is_public: false,
    is_non_profit: false,
    date_founded: "1998",
    enrollment: "Not Reported",
    num_faculty: "Not Reported",
    calendar_type: "Not Reported",
    religious_affiliation: "None",
    has_library: true,
    housing: "Not Reported",
    has_sports_facility: false,
    admission_selection: "Not Reported",
    accepts_internationals: true
  },
  {
    name: "University Adventiste Cosendai",
    acronym: "UAC",
    location: "Nanga-Eboko",
    country_ranking: 12,
    world_ranking: 11939,
    majors: ["Arts and Humanaties", "Science and Technology",
             "Business and Social Sciences", "Medicine and Health"],
    is_public: false,
    is_non_profit: true,
    date_founded: "1996",
    enrollment: "250 - 500",
    num_faculty: "0 - 50",
    calendar_type: "Semester",
    religious_affiliation: "Christian-Adventist",
    has_library: true,
    housing: "Not Reported",
    has_sports_facility: true,
    admission_selection: "Transcripts",
    accepts_internationals: true
  },
  {
    name: "University de Yaounde II",
    acronym: "UYII",
    location: "Soa",
    country_ranking: 13,
    world_ranking: 12018,
    majors: ["Arts and Humanaties", "Science and Technology",
             "Business and Social Sciences", "Medicine and Health"],
    is_public: true,
    is_non_profit: true,
    date_founded: "1962",
    enrollment: "6,000 - 7,000",
    num_faculty: "200 - 300",
    calendar_type: "Not Reported",
    religious_affiliation: "None",
    has_library: true,
    housing: "Not Reported",
    has_sports_facility: false,
    admission_selection: "Transcripts",
    accepts_internationals: true
  },
  {
    name: "University Protestante d'Afrique Centrale",
    acronym: "UPAC",
    location: "Yaounde",
    country_ranking: 14,
    world_ranking: 12264,
    majors: [],
    is_public: false,
    is_non_profit: true,
    date_founded: "1989",
    enrollment: "Not Reported",
    num_faculty: "Not Reported",
    calendar_type: "Not Reported",
    religious_affiliation: "Christian-Protestant",
    has_library: true,
    housing: "Not Reported",
    has_sports_facility: false,
    admission_selection: "Not Reported",
    accepts_internationals: true
  },
  {
    name: "Universite de Yaounde Sud Joseph NDI SAMBA",
    acronym: "NDI-SAMBA",
    location: "Yaounde",
    country_ranking: 15,
    world_ranking: 13161,
    majors: [],
    is_public: false,
    is_non_profit: false,
    date_founded: "1996",
    enrollment: "Not Reported",
    num_faculty: "Not Reported",
    calendar_type: "Not Reported",
    religious_affiliation: "None",
    has_library: true,
    housing: "Not Reported",
    has_sports_facility: false,
    admission_selection: "Not Reported",
    accepts_internationals: true
  }
]