# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'CommonApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CommonApp

  #pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  pod 'ReactNativeLocalization', :path => '../node_modules/react-native-localization'

  target 'CommonAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.9.0'
  pod 'Firebase/Auth', '~> 5.9.0'
  pod 'Firebase/Database', '~> 5.9.0'
  pod 'GoogleAppMeasurement', '~> 5.2.0'
  pod 'GoogleSignIn'
end

target 'CommonApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CommonApp-tvOS

  target 'CommonApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
